# Generated by Django 5.0.9 on 2024-09-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0013_delete_uploadeddocument'),
        ('wibekwa', '0003_alter_articlepage_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='show_doc_link',
            field=models.BooleanField(default=True, help_text="Show the document link automatically.  One reason to set false would be you're already placing a link in the body", verbose_name='show doc link'),
        ),
    ]
