# Generated by Django 5.0.9 on 2024-09-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0004_articlepage_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTagIndexPage',
        ),
    ]
