# Generated by Django 5.0.9 on 2024-09-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0006_blogstatictagsindexpage_top_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='nonblogpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='summary',
            field=models.CharField(blank=True, help_text='A summary to be displayed instead of the body for index views', max_length=250),
        ),
        migrations.AddField(
            model_name='nonblogpage',
            name='summary',
            field=models.CharField(blank=True, help_text='A summary to be displayed instead of the body for index views', max_length=250),
        ),
    ]
