# Generated by Django 5.0.9 on 2024-09-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0009_articlestatictagsindexpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatictagsindexpage',
            name='top_tag',
        ),
        migrations.RemoveField(
            model_name='articlestatictagsindexpage',
            name='top_tag_title',
        ),
        migrations.AlterField(
            model_name='articlestatictagsindexpage',
            name='tag_titles_string',
            field=models.CharField(blank=True, help_text='A comma separated list of titles to be used instead of the tag names', max_length=255, verbose_name='tag titles'),
        ),
    ]
