# Generated by Django 5.0.9 on 2024-09-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0010_remove_articlestatictagsindexpage_top_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestatictagsindexpage',
            name='first_group_is_special',
            field=models.BooleanField(default=False, help_text='If the first group is expected to be treated differetly from the others.  Implementation may vary by template app', verbose_name='first group is special'),
        ),
    ]
