# Generated by Django 5.0.9 on 2024-10-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0011_articlestatictagsindexpage_show_body_in_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatictagsindexpage',
            name='show_body_in_index',
            field=models.IntegerField(default=0, help_text='The group number up to which articles will show the entire body instead of the summary', verbose_name='show body instead of summary'),
        ),
    ]
