# Generated by Django 5.0.9 on 2024-09-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0012_templatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='show_pagetitle',
            field=models.BooleanField(default=True, help_text='If the page title should be shown'),
        ),
        migrations.AddField(
            model_name='articlestatictagsindexpage',
            name='group_titles_string',
            field=models.CharField(blank=True, help_text='A comma separated list of titles to be used for tag groups', max_length=255, verbose_name='group titles'),
        ),
        migrations.AddField(
            model_name='articlestatictagsindexpage',
            name='show_pagetitle',
            field=models.BooleanField(default=True, help_text='If the page title should be shown'),
        ),
        migrations.AlterField(
            model_name='articlestatictagsindexpage',
            name='tag_titles_string',
            field=models.CharField(blank=True, help_text='A comma separated list of titles to be used instead of the tag names - not separated by group', max_length=255, verbose_name='tag titles'),
        ),
        migrations.AlterField(
            model_name='templatesettings',
            name='theme_color',
            field=models.CharField(default='black', help_text='The theme color. This should match the base name of a css file in a static folder wibekwa/css. Ex "blue" if there is a wibekwa/css/blue.css', max_length=30, verbose_name='theme color'),
        ),
    ]
