# Generated by Django 5.0.9 on 2024-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0012_alter_articlestatictagsindexpage_show_body_in_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatictagsindexpage',
            name='first_group_is_special',
        ),
        migrations.RemoveField(
            model_name='articlestatictagsindexpage',
            name='repeat_ArticlePages',
        ),
        migrations.AddField(
            model_name='articlestatictagsindexpage',
            name='apply_special_formatting',
            field=models.IntegerField(default=False, help_text='The group number up to which special formatting should be applied.  Implementation may vary by template app', verbose_name='apply special formatting'),
        ),

    ]
