# Generated by Django 5.0.9 on 2024-10-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0013_remove_articlestatictagsindexpage_first_group_is_special_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'Article'},
        ),
        migrations.AlterField(
            model_name='sidebararticlepage',
            name='embed_frame_style',
            field=models.CharField(blank=True, default='width:90%; height:1600px;', help_text='For pages with an iFrame, styling for the frame', max_length=255, verbose_name='frame style'),
        ),
        migrations.AlterField(
            model_name='sidebararticlepage',
            name='embed_url',
            field=models.URLField(blank=True, help_text='For pages with an iFrame, the URL of the embedded contnet', max_length=765, verbose_name='embed target URL'),
        ),
    ]
