# Generated by Django 5.0.9 on 2024-09-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wibekwa', '0013_articleindexpage_show_pagetitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesettings',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_settings', to='wagtailcore.site'),
        ),
    ]
