# Generated by Django 5.0.9 on 2024-10-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0014_alter_articlepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='favicon',
            field=models.CharField(blank=True, help_text="The path to the favicon. If static, precede with 'static:' ex: static:images/favicon.ico", max_length=125, verbose_name='path to favicon'),
        ),
    ]
