# Generated by Django 5.0.9 on 2024-09-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0015_sitetemplatesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateSettings',
        ),
    ]
