# Generated by Django 5.0.9 on 2025-01-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0016_alter_articlepage_body_sf_alter_freearticlepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepagegalleryimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='show_main_image',
            field=models.BooleanField(default=True, help_text="Show the first gallery image as the article's main image", verbose_name='show main image'),
        ),
        migrations.AddField(
            model_name='articlepagegalleryimage',
            name='alt_text',
            field=models.TextField(blank=True, max_length=250, verbose_name='alt text'),
        ),
    ]
