# Generated by Django 5.0.9 on 2024-09-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('wibekwa', '0016_delete_templatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
