# Generated by Django 5.0.9 on 2024-12-01 14:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0017_articlecommentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='honeypot_error_message',
            field=models.CharField(blank=True, default='If you are a person, please read the notes and retry', help_text='The name or comma-separated list of names for the field or fields to be left blank by humans in order to trap bots. The field(s) should be single-line required=False', max_length=255, verbose_name='honeypot error message'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='honeypot_field_names',
            field=models.CharField(blank=True, help_text='The name or comma-separated list of names for the field or fields to be left blank by humans in order to trap bots. The field(s) should be single-line required=False', max_length=255, verbose_name='honeypot'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='honeypot_intro',
            field=wagtail.fields.RichTextField(blank=True, default='Note: This form has a field or fields which should be left unfilled. In order to trap automatic form fillers, these fields are not marked but a person should be able to figure out which those are', help_text='Explain to visitors that the form has a field or fields which humans should realize are to be left blank'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text="Enter something like a summary of the form's purpose or general instructions for filling it out. If your form contains honeypots, explain that the form has fields or a field which should be left blank"),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Enter text to be shown after the form is submitted'),
        ),
    ]
