# Generated by Django 5.0.9 on 2025-01-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0017_remove_articlepagegalleryimage_caption_and_more'),
        ('wibekwa', '0018_formpage_honeypot_error_message_and_more'),
    ]

    operations = [
    ]
