# Generated by Django 5.0.9 on 2024-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0018_sitetemplatesettings_banner_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='banner_text',
            field=models.CharField(blank=True, help_text='The alt text to be displayed if there is a banner image, or the text to be displayed if there is no image', max_length=80, verbose_name='banner_text'),
        ),
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='footer_text',
            field=models.CharField(blank=True, help_text='The footer text.  This may be split into a list using footer_text_separator', max_length=255, verbose_name='footer text'),
        ),
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='footer_text_separator',
            field=models.CharField(blank=True, default=';', help_text='The characters by which the footer text will be split.  This is optional', max_length=2, verbose_name='footer text separator'),
        ),
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='site_description',
            field=models.CharField(blank=True, help_text='The site description to be displayed near the banner image or banner text', max_length=80, verbose_name='site description'),
        ),
    ]
