# Generated by Django 5.0.9 on 2025-01-22 22:02

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0019_merge_20250102_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='body_md',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
            preserve_default=False,
        ),
    ]
