# Generated by Django 5.1.7 on 2025-03-19 16:49

import wagtail.fields
import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0020_articlepage_body_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body_md',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='A alternative markdown version of the body both this and the main body will be displayed if both have content'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body_sf',
            field=wagtail.fields.StreamField([('paragraph_block', 0), ('heading_block', 3), ('document_block', 4), ('quote_block', 5), ('image_block', 10), ('external_image_block', 12), ('embed_block', 13), ('table', 14)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['link', 'bold', 'italic', 'ol', 'ul'], 'icon': 'pilcrow'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading_text', 1), ('size', 2)]], {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 5: ('wagtail.blocks.BlockQuoteBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7), ('attribution', 7), ('alt', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.URLBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('url', 11), ('caption', 7), ('attribution', 7), ('alt', 8), ('link', 9)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media'}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}, help_text="The body of the article.  Press the + sign to create content.  Use 'Paragraph block' if you're not sure which type of block to use", verbose_name='body'),
        ),
    ]
