# Generated by Django 5.0.9 on 2024-09-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('wibekwa', '0022_formpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='banner_image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='banner_text',
            field=models.CharField(blank=True, default='Wibekwa', help_text='The alt text to be displayed if there is a banner image, or the text to be displayed if there is no image', max_length=80, verbose_name='banner_text'),
        ),
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='Created wth Wagtail and Wibekwa', help_text='The footer text.  This may be split into a list using footer_text_separator', max_length=255, verbose_name='footer text'),
        ),
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='site_description',
            field=models.CharField(blank=True, default='New Wibewa Wagtail Blog', help_text='The site description to be displayed near the banner image or banner text', max_length=80, verbose_name='site description'),
        ),
    ]
