# Generated by Django 5.1.7 on 2025-03-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0022_alter_articlepage_body_md_alter_articlepage_body_sf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebararticlepage',
            old_name='body',
            new_name='body_rt',
        ),
    ]
