# Generated by Django 5.0.9 on 2024-09-24 23:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wibekwa', '0023_alter_sitetemplatesettings_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('target_url', models.URLField(help_text='The URL of the embedded contnet', verbose_name='Target URL')),
                ('framestyle', models.CharField(blank=True, help_text='Styling for the frame', max_length=255, verbose_name='Frame Style')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
