# Generated by Django 5.1.7 on 2025-03-19 22:24

import wagtail.fields
import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0023_rename_body_sidebararticlepage_body_rt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebararticlepage',
            name='body_md',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='A markdown version of the body. Both this and the richtext version body will be displayed if they have content'),
        ),
        migrations.AlterField(
            model_name='sidebararticlepage',
            name='body_rt',
            field=wagtail.fields.RichTextField(blank=True, help_text='A rich text version of the body. Both this and the markdown version body will be displayed if they have content'),
        ),
    ]
