# Generated by Django 5.1.7 on 2025-03-20 15:04

import datetime
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
        ('wibekwa', '0024_sidebararticlepage_body_md_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freearticlepage',
            options={'verbose_name': 'Free Article'},
        ),
        migrations.AddField(
            model_name='freearticlepage',
            name='body_md',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='A markdown version of the body. Both this and the streamfield version body will be displayed if they have content'),
        ),
        migrations.AddField(
            model_name='freearticlepage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='freearticlepage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='freearticlepage',
            name='show_doc_link',
            field=models.BooleanField(default=True, help_text="Show the document link automatically.  One reason to set false would be you're already placing a link in the body", verbose_name='show doc link'),
        ),
        migrations.AddField(
            model_name='freearticlepage',
            name='show_gallery',
            field=models.BooleanField(default=True, help_text='Show the gallery', verbose_name='show doc link'),
        ),
        migrations.AddField(
            model_name='freearticlepage',
            name='show_main_image',
            field=models.BooleanField(default=True, help_text="Show the first gallery image as the article's main image", verbose_name='show main image'),
        ),
        migrations.AlterField(
            model_name='freearticlepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph_block', 0), ('heading_block', 3), ('document_block', 4), ('quote_block', 5), ('image_block', 10), ('external_image_block', 12), ('embed_block', 13), ('table', 14)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['link', 'bold', 'italic', 'ol', 'ul'], 'icon': 'pilcrow'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading_text', 1), ('size', 2)]], {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 5: ('wagtail.blocks.BlockQuoteBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7), ('attribution', 7), ('alt', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.URLBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('url', 11), ('caption', 7), ('attribution', 7), ('alt', 8), ('link', 9)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media'}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}, help_text='A streamfield version of the body. Both this and the markdown version body will be displayed if they have content'),
        ),
        migrations.CreateModel(
            name='FreeArticlePageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.TextField(blank=True, max_length=250, verbose_name='alt text')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='wibekwa.freearticlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
