# Generated by Django 5.1.7 on 2025-03-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0025_alter_freearticlepage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freearticlepage',
            old_name='body',
            new_name='body_sf',
        ),
    ]
