# Generated by Django 5.0.9 on 2024-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtagsindexpage',
            name='grouped_tag_names_string',
        ),
        migrations.AlterField(
            model_name='blogtagsindexpage',
            name='included_tag_names_string',
            field=models.CharField(blank=True, help_text='A comma separated list of tags to be included in this page which can also be grouped - separate groups with semicolon', max_length=255, verbose_name='tags included'),
        ),
    ]
