# Generated by Django 5.0.9 on 2024-09-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0005_rename_blogtagsindexpage_blogstatictagsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstatictagsindexpage',
            name='top_tag',
            field=models.CharField(blank=True, help_text='A tag to be included in which the posts of this tag are specially featured', max_length=30, verbose_name='tags included as top'),
        ),
        migrations.AddField(
            model_name='blogstatictagsindexpage',
            name='top_tag_title',
            field=models.CharField(blank=True, help_text='The title for the top tag', max_length=30, verbose_name='top tag title'),
        ),
    ]
