# Generated by Django 5.0.9 on 2024-09-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wibekwa', '0008_remove_blogpagetag_content_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStaticTagsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('top_tag', models.CharField(blank=True, help_text='A tag to be included in which the articles of this tag are specially featured', max_length=30, verbose_name='tags included as top')),
                ('included_tag_names_string', models.CharField(blank=True, help_text='A comma separated list of tags to be included in this page which can also be grouped - separate groups with semicolon', max_length=255, verbose_name='tags included')),
                ('top_tag_title', models.CharField(blank=True, help_text='The title for the top tag', max_length=30, verbose_name='top tag title')),
                ('tag_titles_string', models.CharField(blank=True, help_text='A comma separated list of titles to be used instead of the tag names', max_length=255, verbose_name='tags titles')),
                ('separate_tag_groups', models.BooleanField(default=True, help_text='If the ArticlePages should be separated by tag')),
                ('repeat_ArticlePages', models.BooleanField(default=True, help_text='If separated by tag, if ArticlePages that have multiple included tags should be repeated')),
                ('show_tag_titles', models.BooleanField(default=True, help_text='If the tag name should be displayed as a title to accompany the ArticlePages')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='ArticleIndexPage',
        ),
        migrations.RenameModel(
            old_name='BlogTagIndexPage',
            new_name='ArticleTagIndexPage',
        ),
        migrations.RenameField(
            model_name='sitespecificimportantpages',
            old_name='blog_index_page',
            new_name='article_index_page',
        ),
        migrations.DeleteModel(
            name='BlogStaticTagsIndexPage',
        ),
    ]
