# Generated by Django 5.0.9 on 2024-09-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0017_sitetemplatesettings_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='banner_image_width',
            field=models.CharField(blank=True, default='50%', help_text='A css value representing the width of the banner image', max_length=20),
        ),
    ]
