# Generated by Django 5.0.9 on 2024-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0020_sitetemplatesettings_show_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetemplatesettings',
            name='banner_image_width',
        ),
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='banner_image_style',
            field=models.CharField(blank=True, default='50%', help_text='Styling for the banner image or if a single value, A css value representing the width of the banner image', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='footer_text_separator',
            field=models.CharField(blank=True, default=';', help_text='The character by which the footer text will be split into a list.  This is optional', max_length=2, verbose_name='footer text separator'),
        ),
    ]
