# Generated by Django 5.0.9 on 2024-09-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0028_articlepage_embed_frame_style_articlepage_embed_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbedPage',
        ),
    ]
