# Generated by Django 5.0.9 on 2024-09-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa', '0030_freearticlepage_remove_nonblogpagegalleryimage_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wibekwa.articlepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wibekwa.articlepage',),
        ),
        migrations.RemoveField(
            model_name='nonblogpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='nonblogpagegalleryimage',
            name='image',
        ),
        migrations.DeleteModel(
            name='NonBlogPage',
        ),
        migrations.DeleteModel(
            name='NonBlogPageGalleryImage',
        ),
    ]
